global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'al-mizan-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
        labels:
          application: 'al-mizan'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # K6 metrics (quand k6 expose en mode statsd/prometheus)
  - job_name: 'k6'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5656']
        labels:
          application: 'k6-load-test'
